/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kanbagıs;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author damla
 */
public class EritrositJ extends javax.swing.JFrame {

    /**
     * Creates new form EritrositJ
     */
    public EritrositJ() {
        initComponents();
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);

        ButtonGroup bg = new ButtonGroup();
        bg.add(evet);
        bg.add(hayır);
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(evet1);
        bg1.add(hayır1);
        ButtonGroup bg2 = new ButtonGroup();
        bg2.add(evet2);
        bg2.add(hayır2);
        ButtonGroup bg3 = new ButtonGroup();
        bg3.add(evet3);
        bg3.add(hayır3);
        ButtonGroup bg4 = new ButtonGroup();
        bg4.add(evet4);
        bg4.add(hayır4);
        ButtonGroup bg5 = new ButtonGroup();
        bg5.add(evet5);
        bg5.add(hayır5);
        this.setLocationRelativeTo(null);
    }


       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        evet = new javax.swing.JRadioButton();
        hayır = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        evet1 = new javax.swing.JRadioButton();
        hayır1 = new javax.swing.JRadioButton();
        evet2 = new javax.swing.JRadioButton();
        hayır2 = new javax.swing.JRadioButton();
        evet4 = new javax.swing.JRadioButton();
        hayır5 = new javax.swing.JRadioButton();
        evet3 = new javax.swing.JRadioButton();
        hayır3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        evet5 = new javax.swing.JRadioButton();
        hayır4 = new javax.swing.JRadioButton();
        sonuc = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        soruA = new javax.swing.JTextField();
        soruC = new javax.swing.JTextField();
        soruB = new javax.swing.JTextField();
        soruD = new javax.swing.JTextField();
        soruE = new javax.swing.JTextField();
        soruF = new javax.swing.JTextField();
        randevu = new javax.swing.JButton();
        geriDon2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eritrosit bağışı için gereken bilgileri doldurunuz");

        evet.setSelected(true);
        evet.setText("Evet");
        evet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evetActionPerformed(evt);
            }
        });

        hayır.setText("Hayır");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        evet1.setSelected(true);
        evet1.setText("Evet");
        evet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evet1ActionPerformed(evt);
            }
        });

        hayır1.setText("Hayır");

        evet2.setSelected(true);
        evet2.setText("Evet");
        evet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evet2ActionPerformed(evt);
            }
        });

        hayır2.setText("Hayır");

        evet4.setSelected(true);
        evet4.setText("Evet");
        evet4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evet4ActionPerformed(evt);
            }
        });

        hayır5.setText("Hayır");

        evet3.setSelected(true);
        evet3.setText("Evet");
        evet3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evet3ActionPerformed(evt);
            }
        });

        hayır3.setText("Hayır");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        evet5.setSelected(true);
        evet5.setText("Evet");
        evet5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evet5ActionPerformed(evt);
            }
        });

        hayır4.setText("Hayır");

        sonuc.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        sonuc.setForeground(new java.awt.Color(153, 0, 0));
        sonuc.setText("Sonucunu Öğren");
        sonuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sonucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sonucMouseExited(evt);
            }
        });
        sonuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonucActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kanbagıs/eritrosit.jpg"))); // NOI18N

        soruA.setBackground(new java.awt.Color(102, 0, 0));
        soruA.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        soruA.setForeground(new java.awt.Color(255, 255, 255));
        soruA.setText("Kendinizi sağlıklı hissediyor musunuz ? ");
        soruA.setCaretColor(new java.awt.Color(255, 255, 255));
        soruA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soruAActionPerformed(evt);
            }
        });

        soruC.setBackground(new java.awt.Color(102, 0, 0));
        soruC.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        soruC.setForeground(new java.awt.Color(255, 255, 255));
        soruC.setText("Son 5 gün içerisinde ağrı kesici ilacı aldınız mı ?");

        soruB.setBackground(new java.awt.Color(102, 0, 0));
        soruB.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        soruB.setForeground(new java.awt.Color(255, 255, 255));
        soruB.setText("Tehlikeli bir hobiniz var mı ?");
        soruB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soruBActionPerformed(evt);
            }
        });

        soruD.setBackground(new java.awt.Color(102, 0, 0));
        soruD.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        soruD.setForeground(new java.awt.Color(255, 255, 255));
        soruD.setText("Son 1 ay içerisinde aşı oldunuz mu ?");

        soruE.setBackground(new java.awt.Color(102, 0, 0));
        soruE.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        soruE.setForeground(new java.awt.Color(255, 255, 255));
        soruE.setText("Bel soğukluğu nedeniyle tedavi oldunuz mu ?");
        soruE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soruEActionPerformed(evt);
            }
        });

        soruF.setBackground(new java.awt.Color(102, 0, 0));
        soruF.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        soruF.setForeground(new java.awt.Color(255, 255, 255));
        soruF.setText("Daha önce hiç Kongo'da bulunduz mu?");

        randevu.setBackground(new java.awt.Color(255, 255, 255));
        randevu.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        randevu.setForeground(new java.awt.Color(102, 0, 0));
        randevu.setText("RANDEVU AL");
        randevu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                randevuMouseClicked(evt);
            }
        });

        geriDon2.setBackground(new java.awt.Color(255, 255, 255));
        geriDon2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        geriDon2.setForeground(new java.awt.Color(102, 0, 0));
        geriDon2.setText("Geri Dön");
        geriDon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriDon2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                geriDon2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                geriDon2MouseExited(evt);
            }
        });
        geriDon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDon2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(geriDon2)
                        .addGap(88, 88, 88)
                        .addComponent(sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(soruD, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(276, 276, 276)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(276, 276, 276))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(soruC)
                                        .addComponent(soruB)
                                        .addComponent(soruE)
                                        .addComponent(soruF)
                                        .addComponent(soruA))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(evet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(hayır, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(evet1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(hayır1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(evet3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(hayır3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(evet2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(hayır2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(evet4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(hayır4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(evet5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(hayır5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(14, 14, 14))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(506, 506, 506)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(64, 64, 64))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(randevu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(randevu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(evet)
                            .addComponent(soruA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hayır))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(soruB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hayır1)
                            .addComponent(evet1))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soruC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(evet2)
                            .addComponent(hayır2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(evet3)
                                        .addComponent(hayır3))
                                    .addComponent(soruD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(evet4)
                                            .addComponent(hayır4)
                                            .addComponent(soruE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(evet5)
                                            .addComponent(hayır5)
                                            .addComponent(soruF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel7)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sonuc)
                            .addComponent(geriDon2))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void evetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evetActionPerformed

    private void evet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evet1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evet1ActionPerformed

    private void evet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evet2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evet2ActionPerformed

    private void evet4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evet4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evet4ActionPerformed

    private void evet3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evet3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evet3ActionPerformed

    private void evet5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evet5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evet5ActionPerformed

    private void sonucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonucActionPerformed
        int sayac = 0;
        String soruA = hayır.getActionCommand();
        String soruB = evet1.getActionCommand();
        String soruC = evet2.getActionCommand();
        String soruD = evet3.getActionCommand();
        String soruE = evet4.getActionCommand();
        String soruF = evet5.getActionCommand();

        if (hayır.isSelected()) {
            soruA = "Hayır";
            sayac += 1;
        }

        if (evet1.isSelected()) {
            soruB = "Evet";
            sayac += 1;
        }

        if (evet2.isSelected()) {
            soruC = "Evet";
            sayac += 1;
        }

        if (evet3.isSelected()) {
            soruD = "Evet";
            sayac += 1;
        }

        if (evet4.isSelected()) {
            soruE = "Hayır";
            sayac += 1;
        }

        if (evet5.isSelected()) {
            soruF = "Evet";
            sayac += 1;
        }
        if (sayac >= 2) {
            JOptionPane.showMessageDialog(null, "Kan bağışı yapmaya uygun değilsiniz.");
        } else if (sayac < 2) {
            JOptionPane.showMessageDialog(null, "Kan bağışınızı yapabilirsiniz.");
        }

    }//GEN-LAST:event_sonucActionPerformed

    private void soruAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soruAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soruAActionPerformed

    private void soruBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soruBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soruBActionPerformed

    private void soruEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soruEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soruEActionPerformed

    private void sonucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sonucMouseEntered
        sonuc.setBackground(new Color(0, 100, 200));
    }//GEN-LAST:event_sonucMouseEntered

    private void sonucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sonucMouseExited
        sonuc.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_sonucMouseExited

    private void randevuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_randevuMouseClicked
        RandevuJ randevu = new RandevuJ();
        setVisible(false);
        randevu.setVisible(true);
    }//GEN-LAST:event_randevuMouseClicked

    private void geriDon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriDon2MouseClicked
        TestJ test = new TestJ();
        setVisible(false);
        test.setVisible(true);
    }//GEN-LAST:event_geriDon2MouseClicked

    private void geriDon2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriDon2MouseEntered
        geriDon2.setBackground(new Color(0, 100, 200));
    }//GEN-LAST:event_geriDon2MouseEntered

    private void geriDon2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriDon2MouseExited
        geriDon2.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_geriDon2MouseExited

    private void geriDon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geriDon2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EritrositJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EritrositJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EritrositJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EritrositJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EritrositJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton evet;
    private javax.swing.JRadioButton evet1;
    private javax.swing.JRadioButton evet2;
    private javax.swing.JRadioButton evet3;
    private javax.swing.JRadioButton evet4;
    private javax.swing.JRadioButton evet5;
    private javax.swing.JButton geriDon2;
    private javax.swing.JRadioButton hayır;
    private javax.swing.JRadioButton hayır1;
    private javax.swing.JRadioButton hayır2;
    private javax.swing.JRadioButton hayır3;
    private javax.swing.JRadioButton hayır4;
    private javax.swing.JRadioButton hayır5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton randevu;
    private javax.swing.JButton sonuc;
    private javax.swing.JTextField soruA;
    private javax.swing.JTextField soruB;
    private javax.swing.JTextField soruC;
    private javax.swing.JTextField soruD;
    private javax.swing.JTextField soruE;
    private javax.swing.JTextField soruF;
    // End of variables declaration//GEN-END:variables
}
