/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kanbagıs;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author damla
 */
public class KanBagisUygulamasi extends javax.swing.JFrame {

    /**
     * Creates new form KanBagısUygulaması
     */
    public KanBagisUygulamasi() {
        initComponents();
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        kullanıcıAd.setBorder(border);
        sifre.setBorder(border);
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        test_et = new javax.swing.JButton();
        iconA = new javax.swing.JLabel();
        iconB = new javax.swing.JLabel();
        giris_yap = new javax.swing.JButton();
        kullanıcıAd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sifre = new javax.swing.JPasswordField();
        kayda_gec = new javax.swing.JLabel();
        doktor_giris = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KAN BAĞIŞI YAPMAK İSTER MİSİNİZ ? ");

        test_et.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        test_et.setForeground(new java.awt.Color(153, 0, 0));
        test_et.setText("Hemen kendini test et");
        test_et.setToolTipText("");
        test_et.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                test_etMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                test_etMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test_etMouseExited(evt);
            }
        });

        iconA.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        iconA.setForeground(new java.awt.Color(255, 255, 255));
        iconA.setText("Kullanıcı Adı:");

        iconB.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        iconB.setForeground(new java.awt.Color(255, 255, 255));
        iconB.setText("Şifre:");

        giris_yap.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        giris_yap.setForeground(new java.awt.Color(102, 0, 0));
        giris_yap.setText("Giris yap");
        giris_yap.setToolTipText("");
        giris_yap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                giris_yapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                giris_yapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                giris_yapMouseExited(evt);
            }
        });
        giris_yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_yapActionPerformed(evt);
            }
        });

        kullanıcıAd.setForeground(new java.awt.Color(204, 204, 204));
        kullanıcıAd.setText("kullanıcı adı");
        kullanıcıAd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kullanıcıAdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kullanıcıAdFocusLost(evt);
            }
        });
        kullanıcıAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanıcıAdActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                 HAYAT KURTAR");

        sifre.setForeground(new java.awt.Color(204, 204, 204));
        sifre.setText("şifre alanı");
        sifre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sifreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sifreFocusLost(evt);
            }
        });
        sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreActionPerformed(evt);
            }
        });

        kayda_gec.setBackground(new java.awt.Color(255, 255, 255));
        kayda_gec.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        kayda_gec.setForeground(new java.awt.Color(255, 255, 255));
        kayda_gec.setText("    Hesabın yok mu ? Kaydol");
        kayda_gec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayda_gecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kayda_gecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kayda_gecMouseExited(evt);
            }
        });

        doktor_giris.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        doktor_giris.setForeground(new java.awt.Color(102, 0, 0));
        doktor_giris.setText("DOKTOR GİRİŞ");
        doktor_giris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doktor_girisMouseClicked(evt);
            }
        });
        doktor_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktor_girisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(test_et, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconA, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconB, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doktor_giris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kayda_gec, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(sifre)
                            .addComponent(kullanıcıAd)
                            .addComponent(giris_yap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullanıcıAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconA, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconB))
                .addGap(18, 18, 18)
                .addComponent(giris_yap, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doktor_giris)
                .addGap(18, 18, 18)
                .addComponent(kayda_gec)
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(test_et, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kanbagıs/kanBagis.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giris_yapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_yapActionPerformed
        String kullaniciA = kullanıcıAd.getText();
        String sifreA = String.valueOf(sifre.getPassword());
        PreparedStatement st;
        ResultSet rs;
        
        String sorgu = "SELECT * FROM kullanıcı WHERE kullanıcı_ad = ? AND sifre = ?";

        if (kullaniciA.trim().equals("kullanıcı adı")) {
            JOptionPane.showMessageDialog(null, "Kullanıcı Adınızı Giriniz", "Kullanıcı Adı Alanı Boş", 2);
        } else if (sifreA.trim().equals("şifre alanı")) {
            JOptionPane.showMessageDialog(null, "Şifrenizi Giriniz", "Şifre Alanı Boş", 2);
        } else {
            try {
                st = KanBagis.getConnection().prepareStatement(sorgu);
                st.setString(1, kullaniciA);
                st.setString(2, sifreA);
                rs = st.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Kullanıcı adı ve şifre doğru sisteme giriş yapılıyor");
                    TestJ test = new TestJ();
                    setVisible(false);
                    test.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Kullanıcı adı veya şifre yanlış", "Hatalı Giriş", 2);
                }
                st.close();
                rs.close();

            } catch (SQLException ex) {
                Logger.getLogger(KanBagisUygulamasi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(KanBagisUygulamasi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_giris_yapActionPerformed

    private void sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreActionPerformed

    }//GEN-LAST:event_sifreActionPerformed

    private void kullanıcıAdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kullanıcıAdFocusLost
        if (kullanıcıAd.getText().equals("") || kullanıcıAd.getText().toLowerCase().equals("kullanıcı adı")) {
            kullanıcıAd.setText("kullanıcı adı");
            kullanıcıAd.setForeground(new Color(204, 204, 204));
        }
        iconA.setBorder(null);
    }//GEN-LAST:event_kullanıcıAdFocusLost

    private void sifreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sifreFocusLost
        String sifreA = String.valueOf(sifre.getPassword());
        if (sifreA.equals("") || sifreA.toLowerCase().equals("şifre alanı")) {
            sifre.setText("şifre alanı");
            sifre.setForeground(new Color(204, 204, 204));
        }
        iconB.setBorder(null);
    }//GEN-LAST:event_sifreFocusLost

    private void sifreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sifreFocusGained
        String sifreA = String.valueOf(sifre.getPassword());
        if (sifreA.toLowerCase().equals("şifre alanı")) {
            sifre.setText("");
            sifre.setForeground(Color.black);
        }
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        iconB.setBorder(border);
    }//GEN-LAST:event_sifreFocusGained

    private void giris_yapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giris_yapMouseEntered
        giris_yap.setBackground(new Color(0, 100, 200));
    }//GEN-LAST:event_giris_yapMouseEntered

    private void giris_yapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giris_yapMouseExited
        giris_yap.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_giris_yapMouseExited

    private void kullanıcıAdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kullanıcıAdFocusGained
        if (kullanıcıAd.getText().toLowerCase().equals("kullanıcı adı")) {
            kullanıcıAd.setText("");
            kullanıcıAd.setForeground(Color.black);

        }
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        iconA.setBorder(border);

    }//GEN-LAST:event_kullanıcıAdFocusGained

    private void kullanıcıAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanıcıAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullanıcıAdActionPerformed

    private void kayda_gecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayda_gecMouseEntered
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.blue);
        kayda_gec.setBorder(border);
    }//GEN-LAST:event_kayda_gecMouseEntered

    private void kayda_gecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayda_gecMouseExited

    }//GEN-LAST:event_kayda_gecMouseExited

    private void kayda_gecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayda_gecMouseClicked
        KayitJ kayıt = new KayitJ();
        setVisible(false);
        kayıt.setVisible(true);
    }//GEN-LAST:event_kayda_gecMouseClicked

    private void test_etMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test_etMouseClicked
        TestJ test = new TestJ();
        setVisible(false);
        test.setVisible(true);
    }//GEN-LAST:event_test_etMouseClicked

    private void test_etMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test_etMouseEntered
        test_et.setBackground(new Color(0, 100, 200));
    }//GEN-LAST:event_test_etMouseEntered

    private void test_etMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test_etMouseExited
        test_et.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_test_etMouseExited

    private void doktor_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktor_girisActionPerformed
        String kullaniciD = kullanıcıAd.getText();
        String sifreD = String.valueOf(sifre.getPassword());
        PreparedStatement st;
        ResultSet rs;

        String sorgu = "SELECT * FROM doktor_giris WHERE kullanıcı_ad = ? AND sifre = ?";

        if (kullaniciD.trim().equals("kullanıcı adı")) {
            JOptionPane.showMessageDialog(null, "Kullanıcı Adınızı Giriniz", "Kullanıcı Adı Alanı Boş", 2);
        } else if (sifreD.trim().equals("şifre alanı")) {
            JOptionPane.showMessageDialog(null, "Şifrenizi Giriniz", "Şifre Alanı Boş", 2);
        } else {
            try {
                st = KanBagis.getConnection().prepareStatement(sorgu);
                st.setString(1, kullaniciD);
                st.setString(2, sifreD);
                rs = st.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Kullanıcı adı ve şifre doğru sisteme giriş yapılıyor");
                    DoktorGirisJ dg = new DoktorGirisJ();
                    setVisible(false);
                    dg.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Kullanıcı adı veya şifre yanlış", "Hatalı Giriş", 2);
                }
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(KanBagisUygulamasi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(KanBagisUygulamasi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_doktor_girisActionPerformed

    private void giris_yapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giris_yapMouseClicked
        TestJ test = new TestJ();
        setVisible(false);
        test.setVisible(true);
    }//GEN-LAST:event_giris_yapMouseClicked

    private void doktor_girisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doktor_girisMouseClicked
        DoktorGirisJ dg = new DoktorGirisJ();
        setVisible(false);
        dg.setVisible(true);
    }//GEN-LAST:event_doktor_girisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KanBagisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KanBagisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KanBagisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KanBagisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KanBagisUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doktor_giris;
    private javax.swing.JButton giris_yap;
    private javax.swing.JLabel iconA;
    private javax.swing.JLabel iconB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kayda_gec;
    private javax.swing.JTextField kullanıcıAd;
    private javax.swing.JPasswordField sifre;
    private javax.swing.JButton test_et;
    // End of variables declaration//GEN-END:variables
}
