/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kanbagıs;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author damla
 */
public class KayitJ extends javax.swing.JFrame {

    /**
     * Creates new form Kayıt
     */
    public KayitJ() {
        initComponents();
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);

        Border borderA = BorderFactory.createMatteBorder(1, 4, 1, 1, Color.white);
        ad.setBorder(borderA);
        soyad.setBorder(borderA);
        kullanici_adi.setBorder(borderA);
        sifre.setBorder(borderA);
        sifre_onay.setBorder(borderA);
        telefon_no.setBorder(borderA);
        kan_grubu.setBorder(borderA);

        ButtonGroup bg = new ButtonGroup();
        bg.add(erkek);
        bg.add(kadin);
        
        this.setLocationRelativeTo(null);
    }

    boolean kontrol_et() {
        String adA = ad.getText();
        String soyadA = soyad.getText();
        String kullanici_adiA = kullanici_adi.getText();
        String sifreA = String.valueOf(sifre.getPassword());
        String sifreAA = String.valueOf(sifre_onay.getPassword());
        String telefon_noA = telefon_no.getText();
        String kan_grubuA = kan_grubu.getText();
        if (adA.trim().equals("") || soyadA.trim().equals("") || kullanici_adiA.trim().equals("") || sifreA.trim().equals("") || sifreAA.trim().equals("") || telefon_noA.trim().equals("") || kan_grubuA.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Herhangi bir alan boş bırakılamaz", "Hatalı İşlem", 2);
            return false;
        } else if (!sifreA.equals(sifreAA)) {
            JOptionPane.showMessageDialog(null, "Şifreler eşleşmiyor", "Şifre Onayı", 2);
            return false;
        }
        return true;
    }

    boolean kullanici_adini_kontrol_et(String kullanıcı_ad) {
        boolean kullanici_adi_varligi = false;
        PreparedStatement st;
        ResultSet rs;
        String sorgu = "SELECT * FROM kullanıcı WHERE kullanıcı_ad= ?";
        try {
            st = KanBagis.getConnection().prepareStatement(sorgu);
            st.setString(1, kullanıcı_ad);
            rs = st.executeQuery();
            if (rs.next()) {
                kullanici_adi_varligi = true;
                JOptionPane.showMessageDialog(null, "Bu kullanıcı adı alınmış.Başka bir kullanıcı"
                        + " adı deneyin", "Kullanıcı Adı Hatası", 2);
                this.kullanici_adi.setText("");
            }
           st.close();
           rs.close();
        } catch (HeadlessException | SQLException e) {
        } catch (Exception ex) {
            Logger.getLogger(KayitJ.class.getName()).log(Level.SEVERE, null, ex);
        }
        return kullanici_adi_varligi;
    }

    String gorsel_yolu = null;

    public ImageIcon ResizeImageIcon(String gorsel_yolu, byte[] gorsel) {
        ImageIcon imageA = null;
        if (gorsel_yolu != null) {
            imageA = new ImageIcon(gorsel_yolu);
        } else {
            imageA = new ImageIcon(gorsel);
        }
        Image img = imageA.getImage();
        Image img2 = img.getScaledInstance(gorselA.getWidth(), gorselA.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageB = new ImageIcon(img2);
        return imageB;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fotograf_ekle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gorselA = new javax.swing.JLabel();
        kaydol1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        soyad = new javax.swing.JTextField();
        kullanici_adi = new javax.swing.JTextField();
        sifre = new javax.swing.JPasswordField();
        sifre_onay = new javax.swing.JPasswordField();
        telefon_no = new javax.swing.JTextField();
        erkek = new javax.swing.JRadioButton();
        kadin = new javax.swing.JRadioButton();
        kan_grubu = new javax.swing.JTextField();
        kayit_mevcut = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        geriDon2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        fotograf_ekle.setText("Fotoğraf Ekle");
        fotograf_ekle.setToolTipText("");
        fotograf_ekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fotograf_ekleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fotograf_ekleMouseExited(evt);
            }
        });
        fotograf_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotograf_ekleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hesap Fotoğrafı:");

        kaydol1.setText("KAYDOL");
        kaydol1.setToolTipText("");
        kaydol1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kaydol1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kaydol1MouseExited(evt);
            }
        });
        kaydol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydol1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adınız:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Soyadınız:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kullanıcı Adınız:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Şifre:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Şifrenizi Onaylayın:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kan Grubunuz:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefon No:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cinsiyet:");

        ad.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });

        soyad.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        soyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyadActionPerformed(evt);
            }
        });

        kullanici_adi.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        kullanici_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanici_adiActionPerformed(evt);
            }
        });

        sifre.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        sifre_onay.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        telefon_no.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        telefon_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefon_noKeyTyped(evt);
            }
        });

        erkek.setBackground(new java.awt.Color(102, 0, 0));
        erkek.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        erkek.setForeground(new java.awt.Color(255, 255, 255));
        erkek.setSelected(true);
        erkek.setText("ERKEK");

        kadin.setBackground(new java.awt.Color(102, 0, 0));
        kadin.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        kadin.setForeground(new java.awt.Color(255, 255, 255));
        kadin.setText("KADIN");
        kadin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kadinActionPerformed(evt);
            }
        });

        kan_grubu.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        kan_grubu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kan_grubuActionPerformed(evt);
            }
        });

        kayit_mevcut.setBackground(new java.awt.Color(255, 255, 255));
        kayit_mevcut.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        kayit_mevcut.setForeground(new java.awt.Color(255, 255, 255));
        kayit_mevcut.setText("      Kayıtlı mısın ? Giriş Yap ");
        kayit_mevcut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayit_mevcutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kayit_mevcutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kayit_mevcutMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kanbagıs/kayitfoto.jpg"))); // NOI18N

        geriDon2.setBackground(new java.awt.Color(255, 255, 255));
        geriDon2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        geriDon2.setForeground(new java.awt.Color(102, 0, 0));
        geriDon2.setText("Geri Dön");
        geriDon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriDon2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                geriDon2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                geriDon2MouseExited(evt);
            }
        });
        geriDon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDon2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geriDon2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(erkek, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kadin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sifre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soyad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kullanici_adi)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fotograf_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gorselA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(kan_grubu)
                            .addComponent(telefon_no, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sifre_onay, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kaydol1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(kayit_mevcut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ad))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(gorselA, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fotograf_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(31, 31, 31)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(sifre_onay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(telefon_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(kan_grubu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(erkek)
                                .addComponent(kadin)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kaydol1)
                            .addComponent(geriDon2))
                        .addGap(32, 32, 32)
                        .addComponent(kayit_mevcut)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fotograf_ekleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fotograf_ekleMouseEntered

    }//GEN-LAST:event_fotograf_ekleMouseEntered

    private void fotograf_ekleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fotograf_ekleMouseExited

    }//GEN-LAST:event_fotograf_ekleMouseExited

    private void fotograf_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotograf_ekleActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File("user.home"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int sonuc = file.showSaveDialog(null);
        if (sonuc == JFileChooser.APPROVE_OPTION) {
            File secilen_gorsel = file.getSelectedFile();
            String gorsel_yoluA = secilen_gorsel.getAbsolutePath();
            gorselA.setIcon(ResizeImageIcon(gorsel_yoluA, null));
            gorsel_yolu = gorsel_yoluA;
        } else {
            JOptionPane.showMessageDialog(null, "Dosya Seçilmedi", "Dosya Hatası", 2);
        }
    }//GEN-LAST:event_fotograf_ekleActionPerformed

    private void kaydol1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaydol1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_kaydol1MouseEntered

    private void kaydol1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaydol1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_kaydol1MouseExited

    private void kaydol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydol1ActionPerformed
        String adA = ad.getText();
        String soyadA = soyad.getText();
        String telefon_noA = telefon_no.getText();
        String kan_grubuA = kan_grubu.getText();
        String cinsiyetA = "Erkek";
        if (kadin.isSelected()) {
            cinsiyetA = "Kadin";
        }
        String kullanici_adiA = kullanici_adi.getText();
        String sifreA = String.valueOf(sifre.getPassword());
        String sifreAA = String.valueOf(sifre.getPassword());
        if (kontrol_et()) {
            if (!kullanici_adini_kontrol_et(kullanici_adiA)) {
                PreparedStatement st;
                ResultSet rs;
                String sorgu = "INSERT INTO kullanıcı (ad,soyad,telefon_numarası,kan_grubu,cinsiyet,hesap_fotografı,kullanıcı_ad,sifre) VALUES (?,?,?,?,?,?,?,?)";
                try {
                    st = KanBagis.getConnection().prepareStatement(sorgu);
                    st.setString(1, adA);
                    st.setString(2, soyadA);
                    st.setString(3, telefon_noA);
                    st.setString(4, kan_grubuA);
                    st.setString(5, cinsiyetA);
                    if (gorsel_yolu != null) {
                        InputStream gorsel = new FileInputStream(new File(gorsel_yolu));
                        st.setBlob(6, gorsel);

                    } else {
                        JOptionPane.showMessageDialog(null, "Fotoğraf seçilmedi", "Uyarı", 1);
                        st.setNull(6, java.sql.Types.NULL);
                    }
                    st.setString(7, kullanici_adiA);
                    st.setString(8, sifreA);
                    if (st.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "Hesap Oluşturuldu");
                        KanBagisUygulamasi kbu = new KanBagisUygulamasi();
                        setVisible(false);
                        kbu.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Hata:Hesap Oluşturulmadı");
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_kaydol1ActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adActionPerformed

    private void soyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyadActionPerformed

    private void kadinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kadinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kadinActionPerformed

    private void kan_grubuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kan_grubuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kan_grubuActionPerformed

    private void kullanici_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanici_adiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullanici_adiActionPerformed

    private void telefon_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefon_noKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_telefon_noKeyTyped

    private void kayit_mevcutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayit_mevcutMouseClicked
         KanBagisUygulamasi kbu=new KanBagisUygulamasi();
            setVisible(false);
            kbu.setVisible(true);
    }//GEN-LAST:event_kayit_mevcutMouseClicked

    private void kayit_mevcutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayit_mevcutMouseEntered
        Border border=BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        kayit_mevcut.setBorder(border);
    }//GEN-LAST:event_kayit_mevcutMouseEntered

    private void kayit_mevcutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayit_mevcutMouseExited
        kayit_mevcut.setBorder(null);
    }//GEN-LAST:event_kayit_mevcutMouseExited

    private void geriDon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriDon2MouseClicked
        KanBagisUygulamasi kbu = new KanBagisUygulamasi();
        setVisible(false);
        kbu.setVisible(true);
    }//GEN-LAST:event_geriDon2MouseClicked

    private void geriDon2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriDon2MouseEntered
        geriDon2.setBackground(new Color(0, 100, 200));
    }//GEN-LAST:event_geriDon2MouseEntered

    private void geriDon2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriDon2MouseExited
        geriDon2.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_geriDon2MouseExited

    private void geriDon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDon2ActionPerformed
    
    }//GEN-LAST:event_geriDon2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JRadioButton erkek;
    private javax.swing.JButton fotograf_ekle;
    private javax.swing.JButton geriDon2;
    private javax.swing.JLabel gorselA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton kadin;
    private javax.swing.JTextField kan_grubu;
    private javax.swing.JButton kaydol1;
    private javax.swing.JLabel kayit_mevcut;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JPasswordField sifre;
    private javax.swing.JPasswordField sifre_onay;
    private javax.swing.JTextField soyad;
    private javax.swing.JTextField telefon_no;
    // End of variables declaration//GEN-END:variables

}
