/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kanbagıs;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import static kanbagıs.KanBagis.db;

/**
 *
 * @author damla
 */
public class TestJ extends javax.swing.JFrame {

    /**
     * Creates new form TestJ
     */
    public TestJ() {
        initComponents();
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        this.setLocationRelativeTo(null);
    }

    public String ad(String adA) {
        ad.getText();
        return adA;
    }

    public String soyad(String soyadA) {
        soyad.getText();
        return soyadA;
    }

    public String bagisTuru(String bagıs_türüA) {
        bagıs_türü.getText();
        return bagıs_türüA;
    }

    public String kan_grubu(String kan_grubuA) {
        kan_grubu.getText();
        return kan_grubuA;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        soyad = new javax.swing.JTextField();
        bagıs_türü = new javax.swing.JTextField();
        kan_grubu = new javax.swing.JTextField();
        trombosit = new javax.swing.JButton();
        eritrosit = new javax.swing.JButton();
        plazma = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kaydet = new javax.swing.JButton();
        geriDon4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ad:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Soyad:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bağış Türü:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kan Grubu:");

        ad.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });

        soyad.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        bagıs_türü.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        kan_grubu.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        kan_grubu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kan_grubuActionPerformed(evt);
            }
        });

        trombosit.setText("TROMBOSİT");
        trombosit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trombositMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trombositMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trombositMouseExited(evt);
            }
        });
        trombosit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trombositActionPerformed(evt);
            }
        });

        eritrosit.setText("ERİTROSİT");
        eritrosit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eritrositMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eritrositMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eritrositMouseExited(evt);
            }
        });

        plazma.setText("PLAZMA");
        plazma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plazmaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plazmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plazmaMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Aşağıda bulunan bağış türlerinden kendinizi test edebilirsiniz.");

        kaydet.setBackground(new java.awt.Color(255, 255, 255));
        kaydet.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        kaydet.setForeground(new java.awt.Color(102, 0, 0));
        kaydet.setText("KAYDET TESTE BAŞLA");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });

        geriDon4.setBackground(new java.awt.Color(255, 255, 255));
        geriDon4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        geriDon4.setForeground(new java.awt.Color(102, 0, 0));
        geriDon4.setText("Geri Dön");
        geriDon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriDon4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                geriDon4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                geriDon4MouseExited(evt);
            }
        });
        geriDon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDon4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(kan_grubu))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(ad))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soyad)
                                    .addComponent(bagıs_türü)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(geriDon4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(157, 157, 157)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eritrosit, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trombosit, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plazma, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trombosit)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eritrosit)
                    .addComponent(bagıs_türü, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plazma)
                    .addComponent(kan_grubu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaydet)
                    .addComponent(geriDon4))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adActionPerformed

    private void kan_grubuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kan_grubuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kan_grubuActionPerformed

    private void trombositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trombositMouseClicked
        TrombositJ trombosit = new TrombositJ();
        setVisible(false);
        trombosit.setVisible(true);
    }//GEN-LAST:event_trombositMouseClicked

    private void trombositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trombositMouseEntered
        trombosit.setBackground(new Color(0, 100, 200));
    }//GEN-LAST:event_trombositMouseEntered

    private void trombositMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trombositMouseExited
        trombosit.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_trombositMouseExited

    private void trombositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trombositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trombositActionPerformed

    private void eritrositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eritrositMouseClicked
        EritrositJ eritrosit = new EritrositJ();
        setVisible(false);
        eritrosit.setVisible(true);
    }//GEN-LAST:event_eritrositMouseClicked

    private void eritrositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eritrositMouseEntered
        eritrosit.setBackground(new Color(0, 100, 200));
    }//GEN-LAST:event_eritrositMouseEntered

    private void eritrositMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eritrositMouseExited
        eritrosit.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_eritrositMouseExited

    private void plazmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plazmaMouseClicked
        PlazmaJ plazma = new PlazmaJ();
        setVisible(false);
        plazma.setVisible(true);
    }//GEN-LAST:event_plazmaMouseClicked

    private void plazmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plazmaMouseEntered
        plazma.setBackground(new Color(0, 100, 200));
    }//GEN-LAST:event_plazmaMouseEntered

    private void plazmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plazmaMouseExited
        plazma.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_plazmaMouseExited

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        String adA = ad.getText();
        String soyadA = soyad.getText();
        String bagıs_türüA = bagıs_türü.getText();
        String kan_grubuA = kan_grubu.getText();

        PreparedStatement st;
        ResultSet rs;
        String sorgu = "INSERT INTO test (ad,soyad,bagıs_türü,kan_grubu) VALUES (?,?,?,?)";
        try {
            st = KanBagis.getConnection().prepareStatement(sorgu);
            st.setString(1, adA);
            st.setString(2, soyadA);
            st.setString(3, bagıs_türüA);
            st.setString(4, kan_grubuA);

            if (st.executeUpdate() != 0) {
                JOptionPane.showMessageDialog(null, "Bilgileriniz Kaydedildi");
            } else {
                JOptionPane.showMessageDialog(null, "Hata:Hesap Oluşturulmadı");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_kaydetActionPerformed

    private void geriDon4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriDon4MouseClicked
        KanBagisUygulamasi kbu = new KanBagisUygulamasi();
        setVisible(false);
        kbu.setVisible(true);
    }//GEN-LAST:event_geriDon4MouseClicked

    private void geriDon4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriDon4MouseEntered
        geriDon4.setBackground(new Color(0, 100, 200));
    }//GEN-LAST:event_geriDon4MouseEntered

    private void geriDon4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriDon4MouseExited
        geriDon4.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_geriDon4MouseExited

    private void geriDon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDon4ActionPerformed

    }//GEN-LAST:event_geriDon4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JTextField bagıs_türü;
    private javax.swing.JButton eritrosit;
    private javax.swing.JButton geriDon4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kan_grubu;
    private javax.swing.JButton kaydet;
    private javax.swing.JButton plazma;
    private javax.swing.JTextField soyad;
    private javax.swing.JButton trombosit;
    // End of variables declaration//GEN-END:variables
}
